spring:
  application:
    name: api-gateway
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1070/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: HELLO-SERVICE-CLUSTER
    api-b:
      path: /api-b/**
      serviceId: FEIGN-CONSUMER
